Repository Paritosh5876/Hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#43 Create determinant_solver.cpp
  determinant_solver.cpp
Labels: hacktoberfest-accepted

#44 Create Lifespan of housefly
  Python/Lifespan of housefly.py
Labels: good first issue, hacktoberfest-accepted, Write Something About Your Code

#45 Strassens algorithm for matrix multiplication
  C++/strassens algorithm.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#46 Create Banking Management System.py
  Banking Management System.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#49 Create Hello World.rb
  Ruby/Hello World.rb
Labels: hacktoberfest-accepted, hacktober2021-accepted

#48 Create Distanceconverter.py
  Distanceconverter.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#47 Added pascal's triangle program in python folder
  Python/pascals_triangle.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#50 Create Hello World.pl
  Perl/Hello World.pl
Labels: hacktoberfest-accepted, hacktober2021-accepted

#51 Create Binary Search.py
  Python/Binary Search.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#52 Create stack.py
  stack.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#53 Added few java programs, and FaceRecognition using Python
  Java/AlmostPalindrome.java
  Java/CountPairsWithSum.java
  Java/ValidPalindrome.java
  Python/FaceRecognition.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#55 Create virtual_functions.cpp
  C++/virtual_functions.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#54 radixSort.java
  Java/radixSort.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#56 Create HappyNumber.py
  Python/HappyNumber.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#66 Create matrix.java
  BUNCH OF JAVA PROGRAMS/matrix.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#61 BubbleSort.py
  BubbleSort.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#60 dictionary.py
  Python/dictionary.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#67 Create Lap_Timer.py
  Python/Lap_Timer.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#65 Create Merge k Sorted Lists.java
  Java/Merge k Sorted Lists.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#63 Create Valid_Parentheses.py
  Python/Valid_Parentheses.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#69 Added Round_robbin.py
  Python/round_robbin.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#70 Added KadanesAlgo.java
  Java/KadanesAlgo.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#71 Create lambda.py
  Python/lambda.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#72 Create Area of Square.py
  Python/Area of Square.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#74 Create Area and circumference.rb
  Ruby/Area and circumference.rb
Labels: hacktoberfest-accepted, hacktober2021-accepted

#73 News Today Android App
  Mobile Development/News_Today.md
Labels: hacktoberfest-accepted, hacktober2021-accepted

#75 Create Senior Citizen Check.pl
  Perl/Senior Citizen Check.pl
Labels: hacktoberfest-accepted, hacktober2021-accepted

#77 Rename C++/Check_If_A_Given_integer_is_Even_or_Odd/number to C++/Chec…
  C++/Check_If_A_Given_integer_is_Even_or_Odd.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#79 Tactile Keypad program in Java
  Java/Tactile_Keypad.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#80 Create PointOfImpact.java
  PointOfImpact.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#76 Please check out my code...
  Python/replica_remover.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#82 Revert "Please check out my code..."
  Python/replica_remover.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#78 Add Palindrome and Number of n digit stepping numbers
  C++/palindrome.cpp
  C++/stepping_number.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#59 Create volumeofcone
  Java/volumeofcone.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#84 Create check_python_version.py
  Python/check_python_version.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#85 Weather Android App
  Mobile Development/Weather_App.md
Labels: hacktoberfest-accepted, hacktober2021-accepted

#81 Added BFS implementation code in python with step by step comments
  Python/BFS_Algorithm.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#87 Create Find the word a Game.cpp
  C++/Find the word a Game.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#89 Update Find the word a Game.cpp
  C++/Find the word a Game.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#90 Create Snake And Ladder.cpp
  C++/Snake And Ladder.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#91 Create battery details.py
  Python/battery details.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#93 Create Check the screen brightness.py
  Python/Check the screen brightness.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#156 Added functionality, made code better presented
  C/number_triangle.c
Labels: hacktoberfest-accepted, hacktober2021-accepted

#104 Create keylogger.py
  Python/keylogger.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#58 Added a C++ Code for Segment tree
  C++/segment_tree.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#88 Create import_any_python_file_example.py
  Python/import_any_python_file_example.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#94 Added DFS implementation code in python with step by step comments
  Python/DFS_Algorithm.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#95 Create pattern_inverted.cpp
  C++/pattern_inverted.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#96 DuplicateItem Checker in Java
  Java/DuplicateArray.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#97 HandTracking_OpenCV
  Python/HandTracking/HandTracking_main.py
  Python/HandTracking/HandTracking_module.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#150 Check leap year
  C++/leapyear
Labels: hacktoberfest-accepted, hacktober2021-accepted

#98 program for creating and display LinkedList in C
  C/linked_list.c
Labels: hacktoberfest-accepted, hacktober2021-accepted

#111 Create Height_0f_a_binary_tree.cpp
  C++/Height_0f_a_binary_tree.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#166 largest.cpp
  C++/largest.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#147 inverted full pyramid using * in c language
  C/inverted_pyramid.c
Labels: hacktoberfest-accepted, hacktober2021-accepted

#120 Create GuessTheNumber.java
  Java/GuessTheNumber.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#106 Create longestValidParentheses.py
  Python/longestValidParentheses.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#157 adding Code to reverse an array
  C++/ReverseOfArray.cpp
  C++/ReverseOfArray.exe
Labels: hacktoberfest-accepted, hacktober2021-accepted

#168 Reversing of String
  Java/Reverse.java
Labels: hacktoberfest-accepted, hacktober2021-accepted

#130 solution to first missing positive integer
  First_missing_positive_integer.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#108 Create Implement_queues_using_stacks.py
  Python/Implement_queues_using_stacks.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#115 added a ceasar_cipher.cpp file in cpp directory
  C++/Caesar_Cipher.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#116 Menu Driven Queue
  C/Menu Driven Queue
Labels: hacktoberfest-accepted, hacktober2021-accepted

#118 Added sum_of_all_subarray.cpp
  C++/sum_of_all_subarray.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#123 added a cpp code for bubblesort
  C++/bubble_sort.cpp
Labels: hacktoberfest-accepted, hacktober2021-accepted

#119 Decimal number to Binary conversion Program in Python
  Python/binconversion.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#112 Added chatbot and rename ,py to .py in Check Your External IP address
  Python/Check Your External IP address,py
  Python/Check Your External IP address.py
  Python/Random Password Generator.py
  Python/chatbot/chatbot.py
Labels: hacktoberfest-accepted, hacktober2021-accepted

#125 Added Binary Search Tree in java
  Java/binary_search_tree.java
Labels: hacktoberfest-accepted, hacktober2021-accepted
